# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'DockerHub mirror'
description: 'GitHub Action to mirror a DockerHub repo to another registry'
author: 'arvatoaws-labs'
branding:
  color: 'green'
  icon: 'copy'

inputs:

  src-username:
    description: 'Source username'
    required: true
  src-password:
    description: 'Source password'
    required: true
  src-registry:
    description: 'Source registry (eg. docker.io)'
    required: true
    default: docker.io
  src-repo:
    description: 'Source repo (eg. library/busybox)'
    required: true

  dst-username:
    description: 'Destination username'
    required: true
  dst-password:
    description: 'Destination password'
    required: true
  dst-registry:
    description: 'Destination registry (eg. ghcr.io)'
    required: true
    default: ghcr.io
  dst-repo:
    description: 'Destination repo (eg. myrepo/busybox)'
    required: true

  config:
    description: 'configfile to use'
    required: true
    default: config/generic.yaml

runs:
  using: 'composite'
  steps:
  - run: |
      set -e
      #set -x

      export SRC_USER=${{ inputs.src-username }}
      export SRC_PASS=${{ inputs.src-password }}
      export SRC_REGISTRY=${{ inputs.src-registry }}
      export SRC_REPO=${{ inputs.src-repo }}
      export DST_USER=${{ inputs.dst-username }}
      export DST_PASS=${{ inputs.dst-password }}
      export DST_REPO=${{ inputs.dst-repo }}
      export DST_REGISTRY=${{ inputs.dst-registry }}
      export CONFIG=${{ inputs.config }}

      export CURRENT_YEAR=$(date +'%Y')
      export LAST_YEAR=$((CURRENT_YEAR - 1))

      sed -i "s@REPLACE_ME_CURRENT_YEAR@$CURRENT_YEAR@g" $CONFIG
      sed -i "s@REPLACE_ME_LAST_YEAR@$LAST_YEAR@g" $CONFIG

      echo "::group::Config"
      cat $CONFIG
      echo "::endgroup"

      wget -q https://github.com/regclient/regclient/releases/download/v0.5.1/regsync-linux-amd64 && chmod 755 regsync-linux-amd64

      echo "::group::Checking"
      ./regsync-linux-amd64 -c $CONFIG check
      echo "::endgroup"

      echo "::group::Syncing"
      ./regsync-linux-amd64 -c $CONFIG once
      echo "::endgroup"

    shell: bash
