version: 1
creds:
- registry: "{{env \"SRC_REGISTRY\"}}"
  user: "{{env \"SRC_USER\"}}"
  pass: "{{env \"SRC_PASS\"}}"
- registry: "{{env \"DST_REGISTRY\"}}"
  user: "{{env \"DST_USER\"}}"
  pass: "{{env \"DST_PASS\"}}"

defaults:
  ratelimit:
    min: 100
    retry: 15m
  parallel: 2
sync:
  - source: "docker.io/library/almalinux"
    target: "ghcr.io/arvatoaws-labs/almalinux"
    type: repository
    tags:
      allow:
      - "latest"
      - "8"
      - "9"
      - "9.\\d+"
