defaults:
  ratelimit:
    min: 20
    retry: 1m
  parallel: 2
sync:
- source: "{{env \"SRC_REGISTRY\"}}/{{env \"SRC_REPO\"}}"
  target: "{{env \"DST_REGISTRY\"}}/{{env \"DST_REPO\"}}"
  type: repository
  tags:
    allow:
    - "latest"
    - "3.22"
    - "3.22.\\d+"
    - "3.21"
    - "3.21.\\d+"
    - "3.20"
    - "3.20.\\d+"
    - "3.19"
    - "3.19.\\d+"
