version: 1
creds:
- registry: "{{env \"SRC_REGISTRY\"}}"
  user: "{{env \"SRC_USER\"}}"
  pass: "{{env \"SRC_PASS\"}}"
- registry: "{{env \"DST_REGISTRY\"}}"
  user: "{{env \"DST_USER\"}}"
  pass: "{{env \"DST_PASS\"}}"

defaults:
  ratelimit:
    min: 100
    retry: 15m
  parallel: 2
sync:
- source: "{{env \"SRC_REGISTRY\"}}/{{env \"SRC_REPO\"}}"
  target: "{{env \"DST_REGISTRY\"}}/{{env \"DST_REPO\"}}"
  type: repository
  tags:
    allow:
    - "latest"
    - "3.19"
    - "3.19.\\d+"
    - "3.18"
    - "3.18.\\d+"
    - "3.17"
    - "3.17.\\d+"
