defaults:
  ratelimit:
    min: 20
    retry: 1m
  parallel: 2
sync:
- source: "{{env \"SRC_REGISTRY\"}}/{{env \"SRC_REPO\"}}"
  target: "{{env \"DST_REGISTRY\"}}/{{env \"DST_REPO\"}}"
  type: repository
  tags:
    allow:
    - "\\d+"
    - "\\d+.\\d+"
    - "\\d+.\\d+.\\d+"
    - "\\d+-alpine"
    - "\\d+.\\d+-alpine"
    - "\\d+.\\d+.\\d+-alpine"
    - "\\d+-alpine\\d+"
    - "\\d+.\\d+-alpine\\d+"
    - "\\d+.\\d+.\\d+-alpine\\d+"
    - "\\d+-alpine\\d+.\\d+"
    - "\\d+.\\d+-alpine\\d+.\\d+"
    - "\\d+.\\d+.\\d+-alpine\\d+.\\d+"
    - "\\d+-dev"
    - "\\d+.\\d+-dev"
    - "\\d+.\\d+.\\d+-dev"
    - "\\d+-compat"
    - "\\d+.\\d+-compat"
    - "\\d+.\\d+.\\d+-compat"
    deny:
    - ".*-fips$"
    - "^latest$"