defaults:
  ratelimit:
    min: 20
    retry: 1m
  parallel: 2
sync:
- source: "{{env \"SRC_REGISTRY\"}}/{{env \"SRC_REPO\"}}"
  target: "{{env \"DST_REGISTRY\"}}/{{env \"DST_REPO\"}}"
  type: repository
  tags:
    allow:
    - "\\d+"
    - "\\d+\\.\\d+"
    - "\\d+\\.\\d+\\.\\d+"
    - "\\d+(-alpine|-debian)"
    - "\\d+\\.\\d+(-alpine|-debian)"
    - "\\d+\\.\\d+\\.\\d+(-alpine|-debian)"
    - "\\d+(-alpine\\d+|-debian\\d+)"
    - "\\d+\\.\\d+(-alpine\\d+|-debian\\d+)"
    - "\\d+\\.\\d+\\.\\d+(-alpine\\d+|-debian\\d+)"
    - "\\d+(-alpine\\d+\\.\\d+|-debian\\d+\\.\\d+)"
    - "\\d+\\.\\d+(-alpine\\d+\\.\\d+|-debian\\d+\\.\\d+)"
    - "\\d+\\.\\d+\\.\\d+(-alpine\\d+\\.\\d+|-debian\\d+\\.\\d+)"
    deny:
    - ".*-dev$"
    - ".*-fips$"
    - "^latest$"
  forceRecursive: true