defaults:
  ratelimit:
    min: 20
    retry: 1m
  parallel: 2
sync:
- source: "{{env \"SRC_REGISTRY\"}}/{{env \"SRC_REPO\"}}"
  target: "{{env \"DST_REGISTRY\"}}/{{env \"DST_REPO\"}}"
  type: repository
  tags:
    allow:
    - "latest"
    - "mainline.*"
    - "stable.*"
    - "1.\\d+"
    - "1.\\d+.\\d+"
    - "alpine"
    - "alpine.*"
    - "1.\\d+-alpine"
    - "1.\\d+.\\d+-alpine"
    deny:
    - ".*perl.*"
    - "1.1\\d.*"
