defaults:
  ratelimit:
    min: 20
    retry: 1m
  parallel: 2
sync:
- source: "{{env \"SRC_REGISTRY\"}}/{{env \"SRC_REPO\"}}"
  target: "{{env \"DST_REGISTRY\"}}/{{env \"DST_REPO\"}}"
  type: repository
  tags:
    allow:
    - "latest"
    - "3.\\d+.\\d+"
    - "3.\\d+.\\d+-alpine"
    - "3.\\d+.\\d+-slim"
    - "3.\\d+"
    - "3.\\d+-alpine"
    - "3.\\d+-slim"
    - "3-alpine"
    - "3-slim"
    - '2\.7'
    - '2\.7-alpine'
    deny:
    # invalid manifest type
    - "3.5.6-alpine"
    - "3.4.9-alpine"
    - ".*windows.*"
    - ".*nanonserver.*"
    - ".*rc.*"
