defaults:
  ratelimit:
    min: 20
    retry: 1m
  parallel: 6
sync:
- source: "{{env \"SRC_REGISTRY\"}}/{{env \"SRC_REPO\"}}"
  target: "{{env \"DST_REGISTRY\"}}/{{env \"DST_REPO\"}}"
  type: repository
  tags:
    allow:
    - "latest"
    - "alpine"
    deny:
    - ".*windows.*"
    - ".*nanonserver.*"
    - ".*rc.*"
