version: 1
creds:
- registry: "{{env \"SRC_REGISTRY\"}}"
  user: "{{env \"SRC_USER\"}}"
  pass: "{{env \"SRC_PASS\"}}"
- registry: "{{env \"DST_REGISTRY\"}}"
  user: "{{env \"DST_USER\"}}"
  pass: "{{env \"DST_PASS\"}}"

defaults:
  ratelimit:
    min: 100
    retry: 15m
  parallel: 2
sync:
- source: "{{env \"SRC_REGISTRY\"}}/{{env \"SRC_REPO\"}}"
  target: "{{env \"DST_REGISTRY\"}}/{{env \"DST_REPO\"}}"
  type: repository
  tags:
    allow:
    - "latest"
    - "(v)?\\d+.\\d+.\\d+"
    - "(v)?\\d+.\\d+"
    deny:
    - ".*rc.*"
    - ".*windowsservercore.*"
    - ".*nano.*"
    - "(v)?1.*"
    - "(v)?2.0.\\d+"
    - "(v)?2.1.\\d+"
    - "(v)?2.2.\\d+"
    - "(v)?2.3.\\d+"
    - "(v)?2.4.\\d+"
    - "(v)?2.5.\\d+"
    - "(v)?2.6.\\d+"
    - "(v)?2.7.\\d+"
    - "(v)?2.8.\\d+"
