version: 1
creds:
- registry: "{{env \"SRC_REGISTRY\"}}"
  user: "{{env \"SRC_USER\"}}"
  pass: "{{env \"SRC_PASS\"}}"
- registry: "{{env \"DST_REGISTRY\"}}"
  user: "{{env \"DST_USER\"}}"
  pass: "{{env \"DST_PASS\"}}"

defaults:
  ratelimit:
    min: 100
    retry: 15m
  parallel: 2
sync:
- source: "{{env \"SRC_REGISTRY\"}}/{{env \"SRC_REPO\"}}"
  target: "{{env \"DST_REGISTRY\"}}/{{env \"DST_REPO\"}}"
  type: repository
  tags:
    allow:
    - "latest"
    - -"22.04.*"
    - -"18.04.*"
    deny:
    - ".*2021.*"
    - ".*2020.*"
    - ".*201\\d.*"
    - ".*200\\d.*"
