name: alpine

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron: '20 10 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Current Branch Name
      id: get_branch
      run: git rev-parse --abbrev-ref HEAD

    - name: Mirror
      uses: arvatoaws-labs/dockerhub@${{ steps.output.get_branch }}
      with:
        src-username: ${{ secrets.DOCKERHUB_USERNAME }}
        src-password: ${{ secrets.DOCKERHUB_TOKEN }}
        dst-username: ${{ secrets.CR_USERNAME }}
        dst-password: ${{ secrets.CR_PAT }}
        config: config/alpine.yaml

        src-repo: library/alpine
        dst-repo: arvatoaws-labs/alpine
