name: docker-hardened-charts
on:
  workflow_dispatch:
  push:
    branches:
    - master
    - main
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron: '0 13 * * *'

jobs:
  mirror:
    runs-on: arvato
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Get Current Branch Name
      id: get_branch
      run: git rev-parse --abbrev-ref HEAD
    - name: Login to Docker Hub Hardened
      uses: docker/login-action@v4
      with:
        registry: dhi.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Mirror flux chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: flux-chart
        dst-repo: arvatoaws-labs/flux-chart
    - name: Mirror oauth2-proxy chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: oauth2-proxy-chart
        dst-repo: arvatoaws-labs/oauth2-proxy-chart
    - name: Mirror cert-manager chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: cert-manager-chart
        dst-repo: arvatoaws-labs/cert-manager-chart
    - name: Mirror external-dns chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: external-dns-chart
        dst-repo: arvatoaws-labs/external-dns-chart
    # metrics-server
    - name: Mirror metrics-server chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: metrics-server-chart
        dst-repo: arvatoaws-labs/metrics-server-chart
    - name: Mirror traefik chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: traefik-chart
        dst-repo: arvatoaws-labs/traefik-chart
    - name: Mirror external-secrets chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: external-secrets-chart
        dst-repo: arvatoaws-labs/external-secrets-chart
    - name: Mirror kubernetes-cluster-autoscaler chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: kubernetes-cluster-autoscaler-chart
        dst-repo: arvatoaws-labs/kubernetes-cluster-autoscaler-chart
    - name: Mirror kube-prometheus-stack-chart chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: kube-prometheus-stack-chart
        dst-repo: arvatoaws-labs/kube-prometheus-stack-chart
    ##
    - name: Mirror keda chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: keda-chart
        dst-repo: arvatoaws-labs/keda-chart
    - name: Mirror karpenter chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: karpenter-chart
        dst-repo: arvatoaws-labs/karpenter-chart
    - name: Mirror keycloak chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: keycloak-chart
        dst-repo: arvatoaws-labs/keycloak-chart
    - name: Mirror kyverno chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: kyverno-chart
        dst-repo: arvatoaws-labs/kyverno-chart
    - name: Mirror kyverno-policy-reporter chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: kyverno-policy-reporter-chart
        dst-repo: arvatoaws-labs/kyverno-policy-reporter-chart
    - name: Mirror opencost chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: opencost-chart
        dst-repo: arvatoaws-labs/opencost-chart
    - name: Mirror kube-prometheus-stack chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: kube-prometheus-stack-chart
        dst-repo: arvatoaws-labs/kube-prometheus-stack-chart
    - name: Mirror stakater-reloader chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: stakater-reloader-chart
        dst-repo: arvatoaws-labs/stakater-reloader-chart
    - name: Mirror trivy-operator chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: trivy-operator-chart
        dst-repo: arvatoaws-labs/trivy-operator-chart