name: docker-hardened-charts

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
    - master
    - main
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron: '0 13 * * *'

jobs:
  mirror:
    runs-on: arvato
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Get Current Branch Name
      id: get_branch
      run: git rev-parse --abbrev-ref HEAD
    - name: Login to Docker Hub Hardened
      uses: docker/login-action@v3
      with:
        registry: dhi.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # cert-manager
    - name: Mirror cert-manager chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: cert-manager-chart
        dst-repo: arvatoaws-labs/cert-manager-chart-hardened
    # external-dns
    - name: Mirror external-dns chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: external-dns-chart
        dst-repo: arvatoaws-labs/external-dns-chart-hardened
    # metrics-server
    - name: Mirror metrics-server chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: metrics-server-chart
        dst-repo: arvatoaws-labs/metrics-server-chart-hardened
    # traefik
    - name: Mirror traefik chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: traefik-chart
        dst-repo: arvatoaws-labs/traefik-chart-hardened
    # external-secrets
    - name: Mirror external-secrets chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: external-secrets-chart
        dst-repo: arvatoaws-labs/external-secrets-chart-hardened
    # kubernetes-cluster-autoscaler
    - name: Mirror kubernetes-cluster-autoscaler chart
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/chart-hardened.yaml
        src-registry: dhi.io
        src-repo: kubernetes-cluster-autoscaler-chart
        dst-repo: arvatoaws-labs/kubernetes-cluster-autoscaler-chart-hardened
