name: docker-hardened-images
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
    - master
    - main
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron: '0 13 * * *'

jobs:
  mirror:
    runs-on: arvato
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Get Current Branch Name
      id: get_branch
      run: git rev-parse --abbrev-ref HEAD
    - name: Login to Docker Hub Hardened
      uses: docker/login-action@v3
      with:
        registry: dhi.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # cert-manager
    - name: Mirror cert-manager-controller
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: cert-manager-controller
        dst-repo: arvatoaws-labs/cert-manager-controller-hardened
    - name: Mirror cert-manager-cainjector
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: cert-manager-cainjector
        dst-repo: arvatoaws-labs/cert-manager-cainjector-hardened
    - name: Mirror cert-manager-acmesolver
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: cert-manager-acmesolver
        dst-repo: arvatoaws-labs/cert-manager-acmesolver-hardened
    - name: Mirror cert-manager-webhook
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: cert-manager-webhook
        dst-repo: arvatoaws-labs/cert-manager-webhook-hardened

    # external-dns
    - name: Mirror external-dns
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: external-dns
        dst-repo: arvatoaws-labs/external-dns-hardened

    # metrics-server
    - name: Mirror metrics-server
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: metrics-server
        dst-repo: arvatoaws-labs/metrics-server-hardened

    # traefik
    - name: Mirror traefik
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: traefik
        dst-repo: arvatoaws-labs/traefik-hardened

    # keda
    - name: Mirror keda
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: keda
        dst-repo: arvatoaws-labs/keda-hardened
    - name: Mirror keda-metrics-apiserver
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: keda-metrics-apiserver
        dst-repo: arvatoaws-labs/keda-metrics-apiserver-hardened
    - name: Mirror keda-admission-webhooks
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: keda-admission-webhooks
        dst-repo: arvatoaws-labs/keda-admission-webhooks-hardened
    
    # alpine
    - name: Mirror alpine-base
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: alpine-base
        dst-repo: arvatoaws-labs/alpine-base-hardened

    # busybox
    - name: Mirror busybox
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: busybox
        dst-repo: arvatoaws-labs/busybox-hardened
    
    # curl
    - name: Mirror curl
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: curl
        dst-repo: arvatoaws-labs/curl-hardened

    # elasticsearch
    - name: Mirror elasticsearch
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: elasticsearch
        dst-repo: arvatoaws-labs/elasticsearch-hardened

    # golang
    - name: Mirror golang
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: golang
        dst-repo: arvatoaws-labs/golang-hardened
    
    # grafana
    - name: Mirror grafana
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: grafana
        dst-repo: arvatoaws-labs/grafana-hardened

    # liquibase
    - name: Mirror liquibase
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: liquibase
        dst-repo: arvatoaws-labs/liquibase-hardened
    
    # mongodb
    - name: Mirror mongodb
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: mongodb
        dst-repo: arvatoaws-labs/mongodb-hardened

    # nginx-exporter
    - name: Mirror nginx-exporter
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: nginx-exporter
        dst-repo: arvatoaws-labs/nginx-exporter-hardened

    # nginx
    - name: Mirror nginx
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: nginx
        dst-repo: arvatoaws-labs/nginx-hardened

    # nodejs
    - name: Mirror nodejs
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: node
        dst-repo: arvatoaws-labs/node-hardened

    # php
    - name: Mirror php
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: php
        dst-repo: arvatoaws-labs/php-hardened

    # python
    - name: Mirror python
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: python
        dst-repo: arvatoaws-labs/python-hardened
    
    # redis
    - name: Mirror redis
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: redis
        dst-repo: arvatoaws-labs/redis-hardened

    # ruby
    - name: Mirror ruby
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: ruby
        dst-repo: arvatoaws-labs/ruby-hardened

    # rust
    - name: Mirror rust
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: rust
        dst-repo: arvatoaws-labs/rust-hardened

    # valkey
    - name: Mirror valkey
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: valkey
        dst-repo: arvatoaws-labs/valkey-hardened

    # velero-plugin-for-aws
    - name: Mirror velero-plugin-for-aws
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: velero-plugin-for-aws
        dst-repo: arvatoaws-labs/velero-plugin-for-aws-hardened

    # velero
    - name: Mirror velero
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: velero
        dst-repo: arvatoaws-labs/velero-hardened