name: docker-hardened-images
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
    - master
    - main
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron: '0 13 * * *'

jobs:
  mirror:
    runs-on: arvato
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Get Current Branch Name
      id: get_branch
      run: git rev-parse --abbrev-ref HEAD
    - name: Login to Docker Hub Hardened
      uses: docker/login-action@v3
      with:
        registry: dhi.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # cert-manager
    - name: Mirror cert-manager-controller
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: cert-manager-controller
        dst-repo: arvatoaws-labs/cert-manager-controller-hardened
    - name: Mirror cert-manager-cainjector
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: cert-manager-cainjector
        dst-repo: arvatoaws-labs/cert-manager-cainjector-hardened
    - name: Mirror cert-manager-acmesolver
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: cert-manager-acmesolver
        dst-repo: arvatoaws-labs/cert-manager-acmesolver-hardened
    - name: Mirror cert-manager-webhook
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: cert-manager-webhook
        dst-repo: arvatoaws-labs/cert-manager-webhook-hardened
    - name: Mirror cert-manager-startupapicheck
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: cert-manager-startupapicheck
        dst-repo: arvatoaws-labs/cert-manager-startupapicheck-hardened
    # external-dns
    - name: Mirror external-dns
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: external-dns
        dst-repo: arvatoaws-labs/external-dns-hardened
    # metrics-server
    - name: Mirror metrics-server
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: metrics-server
        dst-repo: arvatoaws-labs/metrics-server-hardened
    # traefik
    - name: Mirror traefik
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: traefik
        dst-repo: arvatoaws-labs/traefik-hardened
    # keda
    - name: Mirror keda
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: keda
        dst-repo: arvatoaws-labs/keda-hardened
    - name: Mirror keda-metrics-apiserver
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: keda-metrics-apiserver
        dst-repo: arvatoaws-labs/keda-metrics-apiserver-hardened
    - name: Mirror keda-admission-webhooks
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: keda-admission-webhooks
        dst-repo: arvatoaws-labs/keda-admission-webhooks-hardened
    # kube-prometheus-stack
    - name: Mirror kubectl
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: kubectl
        dst-repo: arvatoaws-labs/kubectl-hardened
    - name: Mirror thanos
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: thanos
        dst-repo: arvatoaws-labs/thanos-hardened
    - name: Mirror prometheus
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: prometheus
        dst-repo: arvatoaws-labs/prometheus-hardened
    - name: Mirror alertmanager
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: alertmanager
        dst-repo: arvatoaws-labs/alertmanager-hardened
    - name: Mirror prometheus-operator
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: prometheus-operator
        dst-repo: arvatoaws-labs/prometheus-operator-hardened
    - name: Mirror node-exporter
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: node-exporter
        dst-repo: arvatoaws-labs/node-exporter-hardened
    - name: Mirror kube-rbac-proxy
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: kube-rbac-proxy
        dst-repo: arvatoaws-labs/kube-rbac-proxy-hardened
    - name: Mirror kube-state-metrics
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: kube-state-metrics
        dst-repo: arvatoaws-labs/kube-state-metrics-hardened
    - name: Mirror grafana
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: grafana
        dst-repo: arvatoaws-labs/grafana-hardened
    - name: Mirror k8s-sidecar
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: k8s-sidecar
        dst-repo: arvatoaws-labs/k8s-sidecar-hardened
    - name: Mirror kube-webhook-certgen
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: kube-webhook-certgen
        dst-repo: arvatoaws-labs/kube-webhook-certgen-hardened
    - name: Mirror prometheus-config-reloader
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: prometheus-config-reloader
        dst-repo: arvatoaws-labs/prometheus-config-reloader-hardened
    # kubernetes-cluster-autoscaler
    - name: Mirror kubernetes-cluster-autoscaler
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: kubernetes-cluster-autoscaler
        dst-repo: arvatoaws-labs/kubernetes-cluster-autoscaler-hardened
    # alpine
    - name: Mirror alpine-base
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: alpine-base
        dst-repo: arvatoaws-labs/alpine-base-hardened
    # busybox
    - name: Mirror busybox
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: busybox
        dst-repo: arvatoaws-labs/busybox-hardened
    # curl
    - name: Mirror curl
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: curl
        dst-repo: arvatoaws-labs/curl-hardened
    # golang
    - name: Mirror golang
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: golang
        dst-repo: arvatoaws-labs/golang-hardened
    # grafana
    - name: Mirror grafana
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: grafana
        dst-repo: arvatoaws-labs/grafana-hardened
    # liquibase
    - name: Mirror liquibase
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: liquibase
        dst-repo: arvatoaws-labs/liquibase-hardened
    # nginx-exporter
    - name: Mirror nginx-exporter
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: nginx-exporter
        dst-repo: arvatoaws-labs/nginx-exporter-hardened
    # nginx
    - name: Mirror nginx
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: nginx
        dst-repo: arvatoaws-labs/nginx-hardened
    # nodejs
    - name: Mirror nodejs
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: node
        dst-repo: arvatoaws-labs/node-hardened
    # php
    - name: Mirror php
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: php
        dst-repo: arvatoaws-labs/php-hardened
    # python
    - name: Mirror python
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: python
        dst-repo: arvatoaws-labs/python-hardened
    # rust
    - name: Mirror rust
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: rust
        dst-repo: arvatoaws-labs/rust-hardened
    # velero-plugin-for-aws
    - name: Mirror velero-plugin-for-aws
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: velero-plugin-for-aws
        dst-repo: arvatoaws-labs/velero-plugin-for-aws-hardened
    # velero
    - name: Mirror velero
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: velero
        dst-repo: arvatoaws-labs/velero-hardened
    # external-secrets
    - name: Mirror external-secrets
      if: always()
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        config: config/dhi.yaml
        src-registry: dhi.io
        src-repo: external-secrets
        dst-repo: arvatoaws-labs/external-secrets-hardened