name: elasticsearch

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron: '10 11 * * 2'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Mirror
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        src-username: ${{ secrets.DOCKERHUB_USERNAME }}
        src-password: ${{ secrets.DOCKERHUB_TOKEN }}
        dst-username: ${{ secrets.CR_USERNAME }}
        dst-password: ${{ secrets.CR_PAT }}
        config: config/generic.yaml

        src-repo: library/elasticsearch
        dst-repo: arvatoaws-labs/elasticsearch
