name: external-auth-server

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron: '30 11 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout
    #   uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
        version: latest
        driver-opts: image=moby/buildkit:master

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: jenkins-arvato
        password: ${{ secrets.CR_PAT }}
    - name: Mirror
      uses: arvatoaws-labs/dockerhub-mirror@v2
      with:
        dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
        dockerhub-repo: travisghansen/external-auth-server
        dest-registry: ghcr.io
        dest-repo: arvatoaws-labs/external-auth-server
        dry-run: 'false'
