name: filebrowser

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron: '0 12 * * 1'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get Current Branch Name
      id: get_branch
      run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"

    - name: Set Action's Uses
      id: set_action_uses
      run: echo "::set-output name=action_uses::arvatoaws-labs/dockerhub-mirror@${{ steps.get_branch.outputs.branch }}"

    - name: Mirror
      uses: ${{ steps.set_action_uses.outputs.action_uses }}
      with:
        src-username: ${{ secrets.DOCKERHUB_USERNAME }}
        src-password: ${{ secrets.DOCKERHUB_TOKEN }}
        dst-username: ${{ secrets.CR_USERNAME }}
        dst-password: ${{ secrets.CR_PAT }}
        config: config/generic.yaml

        src-repo: filebrowser/filebrowser
        dst-repo: arvatoaws-labs/filebrowser
