name: nodejs

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: jenkins-arvato
          password: ${{ secrets.CR_PAT }}
      - name: Mirror
        uses: crazy-max/ghaction-dockerhub-mirror@v1
        with:
          # dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          # dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerhub-repo: node
          dest-registry:  ghcr.io
          dest-repo: arvatoaws-labs/node
          dry-run: 'false'