name: velero-plugin-for-csi

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron: '30 9 * * 1'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Mirror
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        src-username: ${{ secrets.DOCKERHUB_USERNAME }}
        src-password: ${{ secrets.DOCKERHUB_TOKEN }}
        dst-username: ${{ secrets.CR_USERNAME }}
        dst-password: ${{ secrets.CR_PAT }}
        config: config/generic.yaml

        src-repo: velero/velero-plugin-for-csi
        dst-repo: arvatoaws-labs/velero-plugin-for-csi
