name: velero

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron: '40 9 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get Current Branch Name
      id: get_branch
      run: git rev-parse --abbrev-ref HEAD

    - name: Mirror
      uses: arvatoaws-labs/dockerhub-mirror@main
      with:
        src-username: ${{ secrets.DOCKERHUB_USERNAME }}
        src-password: ${{ secrets.DOCKERHUB_TOKEN }}
        dst-username: ${{github.actor}} #$
        dst-password: ${{ secrets.GITHUB_TOKEN }}
        config: config/generic.yaml

        src-repo: velero/velero
        dst-repo: arvatoaws-labs/velero
